// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOzcLZIVvjEsZErVz4Mwib-0XLUX2CTE',
    appId: '1:968300287068:web:97d740476a31231f7cc299',
    messagingSenderId: '968300287068',
    projectId: 'cart-ca8bf',
    authDomain: 'cart-ca8bf.firebaseapp.com',
    storageBucket: 'cart-ca8bf.appspot.com',
    measurementId: 'G-B5N882DMGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC458J4BbXEZetGRqBrKmuNYiat6oRRV78',
    appId: '1:968300287068:android:e936c626b2ef56427cc299',
    messagingSenderId: '968300287068',
    projectId: 'cart-ca8bf',
    storageBucket: 'cart-ca8bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsoH8kUU1uE3s4T25afFvTqjWMtqoz0pc',
    appId: '1:968300287068:ios:ea1037756cc0622b7cc299',
    messagingSenderId: '968300287068',
    projectId: 'cart-ca8bf',
    storageBucket: 'cart-ca8bf.appspot.com',
    iosBundleId: 'com.example.cart',
  );
}
